
services:
  redis:
    image: redis:7
#    ports:
#      - "6379:6379"

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - redis
